name: Deploy HTML to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checksout
        uses: actions/checkout@v4

      - name: show all files
        run: ls -al